name: Publish to GHCR

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  publish:
    name: Publish to GHCR
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: 'write'
      packages: write

    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: github-app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          token: ${{ steps.github-app-token.outputs.token }}
          ref: ${{ github.head_ref }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ steps.github-app-token.outputs.token }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/gh-actions-git-secret-protector:v1.0.0 .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/gh-actions-git-secret-protector:v1.0.0
