name: Check Pull Request

on:
  pull_request:
    branches:
      - master
    paths:
      - action.yml
      - Dockerfile
      - main.sh
      - post.sh

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: github-app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.github-app-token.outputs.token }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false

      - name: Prepare v1 fixture
        run: |
          .github/scripts/pull-request/make-fixture.sh test-filter test-file.txt

      - name: Prepare v2 fixture
        run: |
          .github/scripts/pull-request/make-fixture.sh test-filter-v2 test-file-v2.txt 2

      - name: Modify action.yaml to use local Dockerfile
        run: |
          sed -i '/image:/s/: .*/: Dockerfile/' action.yml
          git config user.email 'dummy@dummy.com'
          git config user.name 'dummy'
          git add .
          git commit --allow-empty-message --message=''

      - name: Build local image
        run: |
          docker build -t git-secret-protector-image .

      - name: Encrypt v1 file in Docker container
        run: |
          docker run -v ${PWD}:/workspace --entrypoint "sh" git-secret-protector-image -c "cd /workspace && git-secret-protector encrypt-files test-filter"

      - name: Verify v1 file is encrypted
        run: |
          .github/scripts/pull-request/assert-encrypted.sh test-file.txt v1

      - name: Run v1 decryption using GitHub Action
        uses: ./
        with:
          filter: test-filter

      - name: Verify v1 round-trip
        run: |
          .github/scripts/pull-request/assert-roundtrip.sh test-file.txt

      - name: Encrypt v2 file in Docker container
        run: |
          docker run -v ${PWD}:/workspace --entrypoint "sh" git-secret-protector-image -c "cd /workspace && git-secret-protector encrypt-files test-filter-v2"

      - name: Verify v2 file is encrypted
        run: |
          .github/scripts/pull-request/assert-encrypted.sh test-file-v2.txt v2

      - name: Run v2 decryption using GitHub Action
        uses: ./
        with:
          filter: test-filter-v2

      - name: Verify v2 round-trip
        run: |
          .github/scripts/pull-request/assert-roundtrip.sh test-file-v2.txt
