---
name: GitHub Actions Plugin Unit Test

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .gitattributes file for testing
        run: |
          echo "test-file.txt filter=test-filter" > .gitattributes
          git add .gitattributes
          git commit --allow-empty-message --message='Add .gitattributes for testing'

      - name: Create a test file for encryption/decryption
        run: |
          echo "This is a secret test file." > test-file.txt
          git add test-file.txt
          git commit --allow-empty-message --message='Add test file for encryption'

      - name: Modify action.yaml to use local Dockerfile
        run: |
          sed -i '/image:/s/: .*/: Dockerfile/' action.yml
          git config user.email 'dummy@dummy.com'
          git config user.name 'dummy'
          git add .
          git commit --allow-empty-message --message=''

      - name: Run git-secret-protector action
        uses: ./
        with:
          filter: 'test-filter'

      - name: Verify decrypted files
        run: |
          if grep -q "This is a secret test file." test-file.txt; then
            echo "Decryption success!"
          else
            echo "Decryption failed!" && exit 1
          fiØ
