---
name: GitHub Actions Plugin Unit Test

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: github-app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.github-app-token.outputs.token }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false

      - name: Create .gitattributes file for testing
        run: |
          echo "test-file.txt filter=test-filter" > .gitattributes

      - name: Generate AES Key and IV using OpenSSL
        run: |
          # Generate AES key (256 bits) and IV (128 bits) using OpenSSL
          AES_KEY=$(openssl rand -hex 32)  # 256 bits for AES-256
          IV=$(openssl rand -hex 16)  # 128 bits (AES block size)

          # Create directory for key/IV storage
          mkdir -p .git_secret_protector/cache

          # Write key and IV to JSON file
          echo "{\"aes_key\": \"$AES_KEY\", \"iv\": \"$IV\"}" > .git_secret_protector/cache/test-filter_key_iv.json

      - name: Create a test file for encryption/decryption
        run: |
          echo "This is a secret test file." > test-file.txt

      - name: Modify action.yaml to use local Dockerfile
        run: |
          sed -i '/image:/s/: .*/: Dockerfile/' action.yml
          git config user.email 'dummy@dummy.com'
          git config user.name 'dummy'
          git add .
          git commit --allow-empty-message --message=''

      - name: Run git-secret-protector action
        uses: ./
        with:
          filter: 'test-filter'

      - name: Verify decrypted files
        run: |
          if grep -q "This is a secret test file." test-file.txt; then
            echo "Decryption success!"
          else
            echo "Decryption failed!" && exit 1
          fiØ
